name: Crowdin Action

on:
  push:
    paths:
      - 'apps/app/public/locales/en/*.json'

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3

      - name: crowdin action
        uses: crowdin/github-action@6db87d404b6a13cd118070f9af29957aa47ee1f3 # 1.5.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACT_PAT }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        with:
          upload_translations: false
          download_translations: false
          localization_branch_name: l10n_crowdin_action
          create_pull_request: false
          pull_request_body: 'New Crowdin pull request with translations'
          pull_request_labels: 'translations'
          pull_request_base_branch_name: ${{ github.ref_name }}
          crowdin_branch_name: ${{ github.ref_name }}
